### ISSUE TITLE
Change fingerprint data format

### ISSUE THREAD

**Issue by mwinokan** [mwinokan/HIPPO#119]
- [x] Needs to be more parseable by residue
- [ ] It doesn't make sense to count multiple ligand features for each protein

### Aim of fingerprints

- [x] Count interactions between protein and ligand
- [ ] Per ligand feature, identify which protein feature is most likely to interact (closest)

### Tasks

- [x] New interaction table
- [x] Interaction class
- [x] InteractionSet class
- [ ] InteractionTable / animal.interactions?
- [x] db.get_interaction
- [x] pose.interactions
- [x] Modify Pose.calculate_interactions
- [x] Modify Pose methods
- [x] Modify PoseSet.interactions
- [x] animal.plot_residue_interactions
- [x] #121 
- [x] animal.plot_interaction_punchcard
- [ ] Only get features that have the correct chain in Target.calculate_features
- [x] #120
