### ISSUE TITLE
Recipe I/O to JSON

### ISSUE THREAD

**Issue by mwinokan** [mwinokan/HIPPO#12]
### Encode:

- Location and name of database
- Compound ID's

### To-Do's

- [x] Recipe.write_json
- [x] Recipe.from_json class method
- [x] Find a way to generate a hash or UUID for the recipe
- [ ] Add a recipe's table to the database?
